### ISSUE TITLE
integration with pydantic

### ISSUE THREAD

**Issue by dzmitry-lahoda** [nanne-aben/strictly_typed_pandas#151]
tried to do:

```
class PydanticDataSet(BaseModel, DataSet[T]):
    pass
```

and failed for simplest classes. may some example how to have DataSet to be BaseModel in case of T alread BaseModel

**Comment by nanne-aben** [comment]
Hmm, I'm not that familiar with pydantic. The example you've provided works for me.

<img width="477" alt="afbeelding" src="https://github.com/nanne-aben/strictly_typed_pandas/assets/47976799/1c236906-ad3d-468e-8156-b971b67d8edc">

Can you provide a minimum example that results in an error? And preferably the error as well?

**Comment by dzmitry-lahoda** [comment]
````
class PydanticDataSet(BaseModel, DataSet[T]):
    pass
    
def read_dummy_data(TEST_DATA_DIR: str = "./") -> AllData:
    pairs = pd.read_csv(TEST_DATA_DIR / "assets_pairs_xyk.csv")
    df = PydanticDataSet[Schema](
        {
            "id": [1, 2, 3],
            "name": ["John", "Jane", "Jack"],
        }
    )
```

**Comment by dzmitry-lahoda** [comment]
```
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
==================================== short test summary info ====================================
FAILED simulation/routers/test_data.py::test_all_data_from_csv - TypeError: BaseModel.__init__() takes 1 positional argument but 2 were given
=========================== 1 failed, 1 passed, 11 warnings in 1.21s ============================
(devenv) bash-5.2$ 
```

**Comment by dzmitry-lahoda** [comment]
Also generic schemas do not work like this `PydanticDataSet[AssetPairsXyk[str, int]]` . Not sure of it limitation of STP or Python. So it would be other request.

1. make generics work
2. dot not fail when dataset inherited from pydantic

**Comment by dzmitry-lahoda** [comment]
@nanne-aben what do you think?

**Comment by nanne-aben** [comment]
Thanks for the example! It's still not quite a minimal example, since I have to make changes to it to actually be able to run it here (e.g. it doesn't have import statements, I don't actually have the file you're trying to load, etc.). That makes it a bit harder for me to answer your question.

To give you an idea, this would have been a minimal example:

```python
from typing import TypeVar
from pydantic import BaseModel
from strictly_typed_pandas import DataSet

T = TypeVar("T")


class PydanticDataSet(BaseModel, DataSet[T]):
    pass


class Schema(BaseModel):
    id: int
    name: str


PydanticDataSet[Schema](
    {
        "id": [1, 2, 3],
        "name": ["John", "Jane", "Jack"],
    }
)
```

And the error:
```
TypeError: BaseModel.__init__() takes 1 positional argument but 2 were given
```

Essentially, since we're doing multiple inherritance here, we're passing all the arguments to both parent classes. So both `BaseModel` and `DataSet[Schema]` will receive the dictionary

```python
{
    "id": [1, 2, 3],
    "name": ["John", "Jane", "Jack"],
}
```

`BaseModel` doesn't expect that dictionary. So we should make it explicit how want the inherritance to work, e.g.:
```python
class PydanticDataSet(BaseModel, DataSet[T]):
    def __init__(self, *args, **kwargs):
        BaseModel.__init__(self)
        DataSet.__init__(self, *args, **kwargs)


PydanticDataSet[Schema](
    {
        "id": [1, 2, 3],
        "name": ["John", "Jane", "Jack"],
    }
)
```

This will run without an error. However, it seems like the schema isn't passed properly now. For example:
```python
PydanticDataSet[Schema](
    {
        "id": ["a", "b", "c"],
        "name": ["John", "Jane", "Jack"],
    }
)
```
Runs without error (but should raise an exception).

If I change the sequence of the inherritance, I do get the error I'm looking for:
```python
class PydanticDataSet(DataSet[T], BaseModel):
    def __init__(self, *args, **kwargs):
        BaseModel.__init__(self)
        DataSet.__init__(self, *args, **kwargs)


PydanticDataSet[Schema](
    {
        "id": ["a", "b", "c"],
        "name": ["John", "Jane", "Jack"],
    }
)
```

```
TypeError: Column id is of type numpy.object, but the schema suggests <class 'int'>
```

But I also get a warning from pydantic
```
GenericBeforeBaseModelWarning: Classes should inherit from `BaseModel` before generic classes (e.g. `typing.Generic[T]`) for pydantic generics to work properly.
  class PydanticDataSet(DataSet[T], BaseModel):
```

I'm not sure what you're trying to achieve with pydantic. Maybe this will work for your purpose, maybe it won't. I might be able to help more, but I'd need some more background.

Hope this helps!

**Comment by dzmitry-lahoda** [comment]
sorry, yeah. thanks. i am from rust. will try out - new to python.

i am trying to allow to integrate webapi and pandas, so easy to shuffle data, typed way, with client generator for rust caller.

**Comment by dzmitry-lahoda** [comment]
feel if to have fastapi(pydanitc openapi) and something pandas/numpy inside, and wanting types easy way.

**Comment by dzmitry-lahoda** [comment]
I mean Pydantic is not composable with StrictlyTypedPandas.

**Comment by nanne-aben** [comment]
I'm not that familiar with pydantic, but couldn't you use pydantic to deal with the API, and somehow convert that to strictly_typed_pandas on the internal? While maybe re-using the schemas? Something like this:

```python
from pydantic import BaseModel
from strictly_typed_pandas import DataSet


class Person(BaseModel):
    id: int
    name: str


def external_to_internal(person: Person) -> DataSet[Person]:
    ...
```

**Comment by dzmitry-lahoda** [comment]
seems like best approach to split api data from algorithmic data for now.

pydantic plugins to handle numpy/pandas on the way out in various repos/issues.

**Comment by dzmitry-lahoda** [comment]
@nanne-aben thank you
