### ISSUE TITLE
Any possibilities to get errors in the IDE?

### ISSUE THREAD

**Issue by early-riser18** [nanne-aben/strictly_typed_pandas#34]
Hi,

I am a fairly junior programmer so apologies in advance if I use the wrong terminology.

First of all, I really like what you have built! I think this is definitely one of the missing pieces for teams working primarily with data frames. 

One of the things I enjoy with `mypy` is their VS Code extension allowing me to get warnings even before I run my code. Is there such functionality for `strictly_typed_pandas`? 

More generally, is there a way to type check the code with strictly_typed_pandas before running it? 

When I run `mypy <filename>` I only get the `mypy` errors. When I run the actual script, then I get the `strictly_typed_pandas`.

Ideally, I would get both `mypy` errors and `strictly_typed_pandas` errors in the same place.

**Comment by nanne-aben** [comment]
Thanks! Great to hear you're enjoying the package!

If I understand correctly, you've set up VSCode such that you're getting mypy errors in the IDE, but somehow the strictly typed pandas errors do not come through?

Two things come to mind. First, not all strictly typed pandas checks are checked during linting, some of them are exclusively done in runtime. The following example should throw a mypy error:

```python
import pandas as pd
from strictly_typed_pandas import DataSet

class Schema:
    id: int
    name: str

def foo(df: DataSet[Schema]) -> DataSet[Schema]:
    # do stuff
    return df

df1 = DataSet[Schema]({"id": [1, 2, 3], "name": ["John", "Jane", "Jack"]})
res1 = foo(df1)

df2 = pd.DataFrame(df1)
res2 = foo(df2)
# mypy(error): Argument 1 to "foo" has incompatible type "DataFrame"; expected "DataSet[Schema]"
```

While it would be awesome if all checks could be done during linting (rather than runtime), it's unfortunately not possible. Still, the combination of linting checks (which give you quick feedback on whether you're consistent in the way you've defined your types) and runtime checks (which enforce that the annotated types are actually true) are very powerful.

If the above also doesn't result in a mypy error in your IDE, then it might be that VSCode is configured to use a python environment that doesn't have strictly typed pandas installed. 

Does this answer your question?
