### ISSUE TITLE
found module but no type hints or library stubs

### ISSUE THREAD

**Issue by galen104** [nanne-aben/strictly_typed_pandas#5]
Hi,
I have some problem using **strictly_typed_pandas**.
I have created a clean environment (I tried with both virtualenv and with poetry), using python 3.9.7, installing just **strictly_typed_pandas**, mypy, numpy and pandas (pandas-stubs is installed).
When I try to check the file with mypy, I always get this error:

```
❯ mypy .\main.py
main.py:3: error: Skipping analyzing "strictly_typed_pandas": found module but no type hints or library stubs
main.py:3: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
```
I have just used a simple code (basically the same in the doc):

```
import numpy as np
import pandas as pd
from strictly_typed_pandas import DataSet
from typeguard import typechecked


class SchemaA:
    name: str

class SchemaB:
    id: np.int64
    name: str

df: DataSet[SchemaA] = DataSet[SchemaA]({"name": ["John", "Jane", "Jack"]})

@typechecked
def test_func(data: DataSet[SchemaA]) -> DataSet[SchemaA]:
    return (
        data.assign(id=lambda df: range(df.shape[0]))
        .pipe(DataSet[SchemaB])
    )

try:
    df2 = test_func(df)
    print(df2)
except TypeError as e:
    print(e)
```

The runtime checking works, the code prints:

```
Type of the return value must be a DataSet[__main__.SchemaA]; got DataSet[__main__.SchemaB] instead
```

but I expect static analysis to work with mypy as well.
Am I missing something?
Thanks.

**Comment by nanne-aben** [comment]
Ah, right, that's a bug. I'll solve it tomorrow! For now, it should work
for you if you run:

mypy --ignore-missing-imports main.py

Let me know if that works!

**Comment by galen104** [comment]
Thanks for the quick reply.
I have already tried to ignore missing imports but it doesn't work.
For example I have tried this code from the doc:

```
class Schema:
    id: int
    name: str

try:
    df = DataSet[Schema]({"id": [1, 2, 3]})
except TypeError as e:
    print(e)
```

As said in the doc, I expect an error message from mypy like this:

```
Schema contains the following columns not present in data: {'name'}
```

but instead I get nothing:

```
❯ poetry run mypy --ignore-missing-imports .\src\examples\jan.py
Success: no issues found in 1 source file
```

Thanks

**Comment by nanne-aben** [comment]
Hmmm, that shouldn't happen that way... Thanks for reporting it, I'll look
into it tomorrow!

**Comment by nanne-aben** [comment]
Alright, I've resolved the issue! It should work now if you update strictly_typed_pandas:
```bash
pip install --upgrade strictly_typed_pandas
```
Turns out that static code analysis using mypy only worked when Strictly Typed Pandas was installed through Github. For it to work when installing through PyPi, I had to specifically package `py.typed` in `setup.py`. Should have tested that better... Anyway, that's resolved now. Thanks again for reporting this!

Of note, in your last example, I wouldn't actually expect any mypy errors. 
```python
from strictly_typed_pandas import DataSet

class Schema:
    id: int
    name: str

df = DataSet[Schema]({"id": [1, 2, 3]})
```
Unfortunately, Strictly Typed Pandas cannot (yet?) check whether the input dictionary matches the expected schema during linting time (it will do so during run-time though). During linting time, it will be aware that `df` is of the type `DataSet[Schema]`, and will report an error whenever you try to do something that doesn't match that. Typically, this happens when you define a function, like in your earlier example (edited for brevity):

```python
import numpy as np
from strictly_typed_pandas import DataSet

class SchemaA:
    name: str

class SchemaB:
    id: np.int64
    name: str

# mypy error: Argument 1 to "pipe" of "NDFrame" has incompatible type "Type[DataSet[Any]]";
# expected "Union[Callable[..., DataSet[SchemaA]], Tuple[Callable[..., DataSet[SchemaA]], str]]"
def test_func(data: DataSet[SchemaA]) -> DataSet[SchemaA]:
    return (
        data.assign(id=lambda df: range(df.shape[0]))
        .pipe(DataSet[SchemaB])
    )
```

Let me know if everything works as expected now! Also, feel free to ask if anything is unclear!

**Comment by galen104** [comment]
With the updated version, the problem is solved, however I have a question.
I often use libraries that add new features to pandas, such as **pyjanitor**.
Considering this toy code:

```
class SchemaIn:
    title: str
    rating: str
    year: np.int64
    runtime: np.int64

class SchemaB:
    title: str
    rating: str
    year: np.int64
    runtime: np.float64
    new_column: np.int64

df_untyped: pd.DataFrame = pd.read_csv('movies.csv')
df: DataSet[SchemaIn] = DataSet[SchemaIn](df_untyped)

@typechecked
def transform(data: DataSet[SchemaIn]) -> DataSet[SchemaIn]:
    return data.transform_column('runtime', np.sqrt).add_column(column_name="new_column", value=2).pipe(DataSet[SchemaIn])

try:
    df2 = transform(df)
    print(df2)
except TypeError as e:
    print(e)
```
During run-time I get:

```
Data contains the following columns not present in schema: {'new_column'}
```

but during linting-time I get no errors at all.
Is there something I can do to make it works?

Thanks.

**Comment by nanne-aben** [comment]
Unfortunately, no, not yet.

Right now, once you perform a function on a `DataSet`, it will reroute that call to its `DataFrame` superclass, and as such return a `DataFrame`. For this reason, Strictly Typed Pandas code currently typically has the following format:
```python
def foo(df: DataSet[SchemaA]) -> DataSet[SchemaB]:
    return (
        df.assign(b=lambda df: df.a + 1)
        # and potentially other transformations,
        # after which we cast it to the output schema
        .pipe(DataSet[SchemaB])
    )
```

As you can see, the static code analysis only applies on the input and the output of the function. This is convenient, because in my experience most mistakes happen between functions: given that you know the input and output schema, you can usually visually inspect whether the middle part works out (and if you do make a mistake there, it should be caught during the run-time checks, hopefully using a small-and-quick unit test). Doing this across functions however is a nightmare though, since the scope is so much bigger (and if you don’t catch it visually, you’d have to rely on much bigger tests to catch these errors).

That said, I do want to move as many checks as possible to the static code analysis. For functions that don’t change the schema, such as `df.fillna()`, this is definitely possible. For functions that do change the schema, such as `df1.join(df2)`, this will be harder, but I think it’s possible using a custom mypy plugin. This is work in progress.

All of that will be tailored to the pandas package though (since I essentially have to annotate the expected return type on a per-function-basis), at least at first. Once I have implemented this for the pandas functions, we could think about how to do this for pandas extensions. For example, maybe we could add these annotations when you
```
pip install strictly_typed_pandas[pyjanitor]
```

Preferably, this would be implemented and maintained together with people who actually use those pandas extensions. So if you’re open to contributing around that time, that would be very welcome!

**Comment by galen104** [comment]
Ok thanks, we can close this issue as it is resolved.
