### ISSUE TITLE
linters and type checkers are not working with the library

### ISSUE THREAD

**Issue by thisismygitrepo** [nanne-aben/strictly_typed_pandas#68]
I'm trying out the library, and I could not get any error from all the linters and type checkers I added to vscode.
The black magic of Python dynamic typing is still intact.
What am I missing here? 

Thanks

```
from strictly_typed_pandas import DataSet


class Schema2:
    id: int
    name: str


def foo2(df: DataSet[Schema2]) -> DataSet[Schema2]:
    df['name'] = df['name'] + 22 + 'fg'
    df.id = df.ix + 'g'
    return df
```

**Comment by nanne-aben** [comment]
Hmm, yeah, that does indeed not throw any linting errors. Can you verify that the following snippet does result in a linting error?

```python
from strictly_typed_pandas import DataSet

class Schema2:
    id: int
    name: str

def foo2(df: DataSet[Schema2]) -> DataSet[Schema2]:
    return df.assign(name=lambda df: df.name + 22 + "fg")
```

What happens in your code snippet is that by using `df['name'] = ...`, you're making inplace modifications. Since these kind of operations could (and in this case will) change the schema, we've disabled all such modifications on `DataSets` (i.e. we've made the `DataSet` immutable). So during runtime, you should actually get an error that this is not allowed and that you should use functions like df.assign() here instead.

However, the linter doesn't know about this. So it's perfectly happy with returning `df` here, since in its view it's still a `DataSet[Schema2]`. When you use `df.assign()` however, it's cast to a `DataFrame` and the linter will start complaining.

I tried to think how we could signal to the linter that it should complain when someone uses the `df['name'] = ...` syntax, but I can't really think of anything unfortunately...

Lemme know if this answers your question!

**Comment by thisismygitrepo** [comment]
I got this from `Pylance`

```
Expression of type "DataFrame" cannot be assigned to return type "DataSet[Schema2]"
  "DataFrame" is incompatible with "DataSet[Schema2]"
 ```
 
 I'm not really a software engineer so I don't feel competent to suggest.

**Comment by nanne-aben** [comment]
That's good, then you are getting strictly_typed_pandas errors on vscode!

Since `assign()` can change the schema, the return type is a `Dataframe` rather than a `DataSet[Schema2]`. You can resolve the linting error by casting adding `.pipe(DataSet[Schema2])`. 

You can get a lot more information about how that works here:
https://strictly-typed-pandas.readthedocs.io/en/latest/getting_started.html

**Comment by nanne-aben** [comment]
Lemme know if you have more questions!

**Comment by nanne-aben** [comment]
Unfortunately, the linting aspect is more limited than that. Let me illustrate what we can do though using your example.

In the above example, it will signal you that you're returning a `DataFrame` instead of a `DataSet[Schema2]`. You can fix that by using:

```python
from strictly_typed_pandas import DataSet

class Schema2:
    id: int
    name: str

def foo2(df: DataSet[Schema2]) -> DataSet[Schema2]:
    return (
        df.assign(name=lambda df: df.name + 22 + "fg")
        .pipe(DataSet[Schema2])
    )
```

Now suppose we run that:
```python
df = DataSet[Schema2](dict(name=["a", "b", "c"], id=[1, 2, 3]))

foo2(df)
```

It will complain during runtime that you're adding integers to strings. It would be great to catch that during linting time, but unfortunately I don't think that's possible in python.

So where's the use of this library then? Suppose we fix the error:
```python
def foo2(df: DataSet[Schema2]) -> DataSet[Schema2]:
    return (
        df.assign(name=lambda df: df.name + "fg")
        .pipe(DataSet[Schema2])
    )
```

The above will now run without trouble. And, assuming we run foo2() regularly (e.g. using a unit test), we can be certain that it indeed returns a `DataSet[Schema2]`. That's where the linting-time checks come in. Suppose that in the future we have to write a `foo3()` that takes as input the output of `foo2()`, we now know for sure which columns and datatypes are in there. And if we make a mistake (for example inputting a `DataSet[Schema3]` in `foo3()`), we will get a linting error.

So it's really the combination of runtime and linting-time checks that makes this powerful.
